"""
Report Generator
Combines all agent outputs into a downloadable PDF and Markdown report.
"""

import os
import json
from datetime import datetime
from fpdf import FPDF

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
REPORTS_DIR = os.path.join(BASE_DIR, "reports")


def _format_value(v) -> str:
    if v is None:
        return "N/A"
    if isinstance(v, float):
        return f"{v:.6f}" if v < 0.001 else f"{v:.4f}"
    return str(v)


def _format_score(v) -> str:
    if v is None or v == "N/A":
        return "N/A"
    try:
        return f"{float(v) / 10.0:.1f}"
    except (ValueError, TypeError):
        return str(v)


# ─── Markdown ────────────────────────────────────────────────────────────────

def generate_markdown(code_stats: dict, energy_data: dict, benchmark_data: dict,
                      sci_scores: dict, recommendation: dict,
                      planner_plan: dict = None, reflection: dict = None) -> str:

    ts    = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    green = recommendation.get("green_score", {})
    proj  = recommendation.get("carbon_projection", {})

    lines = [
        "# GreenDev AI — Sustainability Report",
        f"**Generated:** {ts}  ",
        "",
        "---",
        "",
        "## 1. Code Metrics",
        f"| Metric | Value |",
        f"|---|---|",
        f"| Functions | {code_stats.get('functions', 'N/A')} |",
        f"| Loops | {code_stats.get('loops', 'N/A')} |",
        f"| Nested Loops | {code_stats.get('nested_loops', 'N/A')} |",
        f"| Lines of Code | {code_stats.get('lines', 'N/A')} |",
        f"| Complexity | {code_stats.get('complexity', 'N/A')} |",
        f"| Task Type | {code_stats.get('task_type', 'N/A')} |",
        f"| Recursion | {code_stats.get('recursion', False)} |",
        "",
        "## 2. Energy Measurement (CodeCarbon)",
        f"| Metric | Value |",
        f"|---|---|",
        f"| Energy Consumed | {_format_value(energy_data.get('energy_kwh'))} kWh |",
        f"| CO₂ Emitted | {_format_value(energy_data.get('co2_grams'))} g |",
        f"| Execution Time | {_format_value(energy_data.get('execution_time'))} s |",
        f"| Measurement Mode | {energy_data.get('mode', 'N/A')} |",
        "",
        "## 3. Real RAPL Benchmark (Energy-Languages Dataset)",
        f"| Language | Energy (J) | Time (s) | Memory (MB) |",
        f"|---|---|---|---|",
    ]

    for lang_key, lang_name in [("python", "Python"), ("c", "C"), ("cpp", "C++"), ("java", "Java")]:
        bd = benchmark_data.get(lang_key, {})
        lines.append(
            f"| {lang_name} | {_format_value(bd.get('energy_joules'))} | "
            f"{_format_value(bd.get('time_seconds'))} | {_format_value(bd.get('memory_mb'))} |"
        )

    lines += [
        "",
        "## 4. SCI Scores",
        f"| Metric | Value |",
        f"|---|---|",
        f"| Estimated SCI | {_format_value(sci_scores.get('estimated_sci'))} gCO₂eq/run |",
        f"| Real SCI | {_format_value(sci_scores.get('real_sci'))} gCO₂eq/run |",
        f"| Deviation | {sci_scores.get('deviation_pct', 0)}% |",
        f"| Anomaly Detected | {sci_scores.get('anomaly_detected', False)} |",
        "",
        "## 5. Green Score",
        f"| Dimension | Score |",
        f"|---|---|",
        f"| **Overall** | **{_format_score(green.get('overall', 'N/A'))} / 10** |",
        f"| Performance | {_format_score(green.get('performance', 'N/A'))} / 10 |",
        f"| Energy | {_format_score(green.get('energy', 'N/A'))} / 10 |",
        f"| Carbon | {_format_score(green.get('carbon', 'N/A'))} / 10 |",
        f"| Maintainability | {_format_score(green.get('maintainability', 'N/A'))} / 10 |",
        "",
        "## 6. Carbon Cost Projection",
        f"| Metric | Value |",
        f"|---|---|",
        f"| Per Run | {_format_value(proj.get('per_run_g'))} g CO₂ |",
        f"| Daily Runs (assumed) | {proj.get('daily_runs_assumed', 'N/A')} |",
        f"| Yearly CO₂ (current) | {_format_value(proj.get('yearly_co2_kg'))} kg |",
        f"| Yearly CO₂ (optimized) | {_format_value(proj.get('yearly_co2_kg_optimized'))} kg |",
        f"| Potential Savings | {proj.get('savings_percent', 0)}% |",
        "",
        "---",
        "_Report generated by GreenDev AI — Evidence-Based Green Code Analysis_",
    ]

    if reflection and reflection.get("reflection_note"):
        lines.insert(-2, f"\n> **Planner Note:** {reflection['reflection_note']}")

    return "\n".join(lines)


# ─── PDF ─────────────────────────────────────────────────────────────────────

class GreenDevPDF(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 14)
        self.set_text_color(34, 139, 34)
        self.cell(0, 10, "GreenDev AI - Sustainability Report", align="C", new_x="LMARGIN", new_y="NEXT")
        self.set_text_color(0)
        self.set_font("Helvetica", "", 9)
        self.cell(0, 6, f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
                  align="C", new_x="LMARGIN", new_y="NEXT")
        self.ln(4)
        self.set_draw_color(34, 139, 34)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(6)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150)
        self.cell(0, 10, "GreenDev AI - Evidence-Based Green Code Analysis", align="C")

    def section_title(self, title: str):
        self.set_font("Helvetica", "B", 11)
        self.set_fill_color(220, 240, 220)
        self.set_text_color(20, 100, 20)
        self.cell(0, 8, title, new_x="LMARGIN", new_y="NEXT", fill=True)
        self.set_text_color(0)
        self.ln(2)

    def kv_row(self, key: str, value: str, shade: bool = False):
        self.set_font("Helvetica", "", 9)
        if shade:
            self.set_fill_color(245, 245, 245)
        else:
            self.set_fill_color(255, 255, 255)
        self.cell(70, 7, key, border=1, fill=True)
        self.cell(120, 7, value, border=1, fill=True, new_x="LMARGIN", new_y="NEXT")


def generate_pdf(code_stats: dict, energy_data: dict, benchmark_data: dict,
                 sci_scores: dict, recommendation: dict,
                 reflection: dict = None,
                 output_path: str = None) -> str:

    green = recommendation.get("green_score", {})
    proj  = recommendation.get("carbon_projection", {})

    pdf = GreenDevPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # Section 1 — Code Metrics
    pdf.section_title("1. Code Metrics")
    rows = [
        ("Functions",     str(code_stats.get("functions", "N/A"))),
        ("Loops",         str(code_stats.get("loops", "N/A"))),
        ("Nested Loops",  str(code_stats.get("nested_loops", "N/A"))),
        ("Lines of Code", str(code_stats.get("lines", "N/A"))),
        ("Complexity",    str(code_stats.get("complexity", "N/A"))),
        ("Task Type",     str(code_stats.get("task_type", "N/A"))),
        ("Recursion",     str(code_stats.get("recursion", False))),
    ]
    for i, (k, v) in enumerate(rows):
        pdf.kv_row(k, v, shade=(i % 2 == 0))
    pdf.ln(5)

    # Section 2 — Energy
    pdf.section_title("2. Energy Measurement (CodeCarbon)")
    energy_rows = [
        ("Energy Consumed",    f"{_format_value(energy_data.get('energy_kwh'))} kWh"),
        ("CO2 Emitted",        f"{_format_value(energy_data.get('co2_grams'))} g"),
        ("Execution Time",     f"{_format_value(energy_data.get('execution_time'))} s"),
        ("Measurement Mode",   energy_data.get("mode", "N/A")),
    ]
    for i, (k, v) in enumerate(energy_rows):
        pdf.kv_row(k, v, shade=(i % 2 == 0))
    pdf.ln(5)

    # Section 3 — Benchmark
    pdf.section_title("3. Real RAPL Benchmark (Energy-Languages Dataset)")
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_fill_color(220, 240, 220)
    for col, w in [("Language", 40), ("Energy (J)", 50), ("Time (s)", 50), ("Memory (MB)", 50)]:
        pdf.cell(w, 7, col, border=1, fill=True)
    pdf.ln()

    lang_map = [("python", "Python"), ("c", "C"), ("cpp", "C++"), ("java", "Java")]
    for i, (key, name) in enumerate(lang_map):
        bd = benchmark_data.get(key, {})
        pdf.set_font("Helvetica", "", 9)
        pdf.set_fill_color(245, 245, 245) if i % 2 == 0 else pdf.set_fill_color(255, 255, 255)
        pdf.cell(40, 7, name, border=1, fill=True)
        pdf.cell(50, 7, _format_value(bd.get("energy_joules")), border=1, fill=True)
        pdf.cell(50, 7, _format_value(bd.get("time_seconds")), border=1, fill=True)
        pdf.cell(50, 7, _format_value(bd.get("memory_mb")), border=1, fill=True)
        pdf.ln()
    pdf.ln(5)

    # Section 4 — SCI
    pdf.section_title("4. SCI Scores")
    sci_rows = [
        ("Estimated SCI", f"{_format_value(sci_scores.get('estimated_sci'))} gCO2eq/run"),
        ("Real SCI",      f"{_format_value(sci_scores.get('real_sci'))} gCO2eq/run"),
        ("Deviation",     f"{sci_scores.get('deviation_pct', 0)}%"),
        ("Anomaly",       str(sci_scores.get("anomaly_detected", False))),
    ]
    for i, (k, v) in enumerate(sci_rows):
        pdf.kv_row(k, v, shade=(i % 2 == 0))
    pdf.ln(5)

    # Section 5 — Green Score
    pdf.section_title("5. Green Score")
    score_rows = [
        ("Overall",         f"{_format_score(green.get('overall', 'N/A'))} / 10"),
        ("Performance",     f"{_format_score(green.get('performance', 'N/A'))} / 10"),
        ("Energy",          f"{_format_score(green.get('energy', 'N/A'))} / 10"),
        ("Carbon",          f"{_format_score(green.get('carbon', 'N/A'))} / 10"),
        ("Maintainability", f"{_format_score(green.get('maintainability', 'N/A'))} / 10"),
    ]
    for i, (k, v) in enumerate(score_rows):
        pdf.kv_row(k, v, shade=(i % 2 == 0))
    pdf.ln(5)

    # Section 6 — Carbon Projection
    pdf.section_title("6. Carbon Cost Projection")
    proj_rows = [
        ("Per Run",               f"{_format_value(proj.get('per_run_g'))} g CO2"),
        ("Daily Runs (assumed)",  str(proj.get("daily_runs_assumed", "N/A"))),
        ("Yearly CO2 (current)",  f"{_format_value(proj.get('yearly_co2_kg'))} kg"),
        ("Yearly CO2 (optimized)",f"{_format_value(proj.get('yearly_co2_kg_optimized'))} kg"),
        ("Potential Savings",     f"{proj.get('savings_percent', 0)}%"),
    ]
    for i, (k, v) in enumerate(proj_rows):
        pdf.kv_row(k, v, shade=(i % 2 == 0))

    if reflection and reflection.get("reflection_note"):
        pdf.ln(6)
        pdf.section_title("Planner Reflection Note")
        pdf.set_font("Helvetica", "I", 9)
        pdf.multi_cell(0, 6, reflection["reflection_note"])

    # Save
    if output_path is None:
        os.makedirs(REPORTS_DIR, exist_ok=True)
        output_path = os.path.join(REPORTS_DIR, f"greendev_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf")

    pdf.output(output_path)
    return output_path
